# Generated by Django 3.0.5 on 2021-05-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alat',
            name='gambar',
            field=models.ImageField(blank=True, default='img/default-alat', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='profil/default-profil', null=True, upload_to='profil/'),
        ),
    ]
